image: "artifactory-gojek.golabs.io:6555/cx-mri:2.5.0"

stages:
  - test
  - compress
  - package
  - deploy_integration_docker
services:
 - mongo:3.6

variables:
 MONGO_URI: “mongodb://mongo/rca_monitoring_system_test”
 HOST_NAME: mongo
 APP_BASE_DOCKER_IMAGE: artifactory-gojek.golabs.io:6555/app-mri:2.5.0
 APP_TYPE: "mri"
 
cache:
 key: ${CI_COMMIT_REF_SLUG}
 paths:
  - vendor

test:
  stage: test
  script:
    - apt-get install -y nodejs
    - bundle install
    - bundle exec rspec

compress:
  stage: compress
  variables:
    PACKAGE_JARS: "false"
  script:
    - apt-get install libffi-dev
    - ASSETS_PRECOMPILE="true" compress
  artifacts:
    name: "${CI_PROJECT_NAME}-${APP_VERSION}-${CI_BUILD_REF}"
    paths:
      - ./pkg
      - ./version.txt
    expire_in: 3 days
  only:
   - master
   - tags

package:
  stage: package
  script:
    - package
  tags:
    - package
  only:
    - master
    - tags

docker_deploy_integration_app:
  stage: deploy_integration_docker
  variables:
    APPLICATION_NAME: ledger-server
    DATACENTER_NAME: gojek-integration
  environment:
    name: integration
  script:
    - deploy_containers
  only:
    - master
    - tags
  when: manual

