development:
  clients:
    default:
      database: rca_monitoring_system_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: rca_monitoring_system_test
      hosts:
        - <%= "mongo:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
